spring:
  datasource:
    url: "jdbc:mysql://job1server.crmwjgezfq89.ap-northeast-2.rds.amazonaws.com:3306/job1DB?serverTimezone=Asia/Seoul"
    username: "master"
    password: "u78eytju5!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:mem:job1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    defer-datasource-initialization: true
#  data:
#    web:
#      pageable:
#        max-page-size: 2000
#        default-page-size: 20
#        one-indexed-parameters: true

hodolman:
  jwt-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="
